apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: resumeapp-web-ingress
  namespace: $PR_NAMESPACE
  annotations:
    acme.cert-manager.io/http01-edit-in-place: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - $PR_HOSTNAME
      secretName: resumeapp-pr-api-tls
  rules:
    - host: $PR_HOSTNAME
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: resumeapp-api-service
                port:
                  number: 80
