apiVersion: v1
kind: ConfigMap
metadata:
  name: blackbox-exporter-config
  namespace: $PR_NAMESPACE
data:
  blackbox.yml: |
    modules:
      http_2xx:
        prober: http
        timeout: 5s
        http:
          method: GET
          follow_redirects: true
          preferred_ip_protocol: ip4
