apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  namespace: resumeapp
data:
  datasource.yml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: http://prometheus-service:9090

  dashboard.json: |
    {
      "panels": [
        {
          "type": "graph",
          "title": "Requests",
          "targets": [
            { "expr": "http_requests_received_total" }
          ]
        }
      ]
    }