apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki
  namespace: resumeapp
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  minReadySeconds: 5
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      labels:
        app: loki
    spec:
      containers:
        - name: loki
          image: grafana/loki:3.5.11
          ports:
            - containerPort: 3100
          args:
            - -config.file=/etc/loki/loki-config.yaml
          startupProbe:
            httpGet:
              path: /ready
              port: 3100
            periodSeconds: 5
            failureThreshold: 12
          readinessProbe:
            httpGet:
              path: /ready
              port: 3100
            periodSeconds: 5
            initialDelaySeconds: 5
          livenessProbe:
            httpGet:
              path: /ready
              port: 3100
            periodSeconds: 10
            initialDelaySeconds: 15
          volumeMounts:
            - name: loki-config
              mountPath: /etc/loki/loki-config.yaml
              subPath: loki-config.yaml
            - name: loki-data
              mountPath: /tmp/loki
      volumes:
        - name: loki-config
          configMap:
            name: loki-config
        - name: loki-data
          persistentVolumeClaim:
            claimName: resumeapp-pvc-loki
