apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: resumeapp-pvc-web-dataprotection
  namespace: resumeapp
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 64Mi
