apiVersion: apps/v1
kind: Deployment
metadata:
  name: resumeapp-api
  namespace: resumeapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resumeapp-api
  template:
    metadata:
      labels:
        app: resumeapp-api
    spec:
      containers:
        - name: resumeapp-api
          image: paulawenighofer/resumeapp:$GITHUB_RUN_NUMBER
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: ASPNETCORE_URLS
              value: http://+:8080
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
          envFrom:
            - secretRef:
                name: resume-app-secrets
