apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: resumeapp
spec:
  replicas: 1
  strategy:
    type: Recreate
  minReadySeconds: 5
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus
          ports:
            - containerPort: 9090
          startupProbe:
            httpGet:
              path: /-/ready
              port: 9090
            periodSeconds: 5
            failureThreshold: 12
          readinessProbe:
            httpGet:
              path: /-/ready
              port: 9090
            periodSeconds: 5
            initialDelaySeconds: 5
          livenessProbe:
            httpGet:
              path: /-/healthy
              port: 9090
            periodSeconds: 10
            initialDelaySeconds: 15
          volumeMounts:
            - name: config
              mountPath: /etc/prometheus
            - name: prometheus-data
              mountPath: /prometheus
      volumes:
        - name: config
          configMap:
            name: prometheus-config
        - name: prometheus-data
          persistentVolumeClaim:
            claimName: resumeapp-pvc-prometheus
